# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c920261b8bd853347d35a139cc18c28cfa26733d0d2d97c1e3bbd00b6d0c245ee8cc2b2d7a1cabf5ea83ceb20a5aba8a63e5781b94ef0b355feaf92fc93aa6e

test:
  secret_key_base: 845a04e295945dfbe24408967b8b01a254627dcbcdce3cbf6f739421b9f8359fc875fa179055be9d459f5d62f20f0e52dc802b484c03a5e0d25181e3222d7995

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
